---
version: '2'

#
# Using Rancher
#
# RANCHER_URL=http://RANCHER_HOST:8080 rancher-compose --env-file=.env up
#

services:

  zammad-backup:
    scale: 1
    start_on_create: true

  zammad-elasticsearch:
    scale: 1
    start_on_create: true

  zammad-init:
    scale: 1
    start_on_create: true

  zammad-memcached:
    scale: 1
    start_on_create: true

  zammad-nginx:
    scale: 1
    start_on_create: true

  zammad-postgresql:
    scale: 1
    start_on_create: true

  zammad-scheduler:
    scale: 1
    start_on_create: true

  zammad-railsserver:
    scale: 1
    start_on_create: true

  zammad-websocket:
    scale: 1
    start_on_create: true
